version: '3.8'
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - ./kafka:/bitnami/kafka
    environment:
      - BITNAMI_DEBUG=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=INTERNAL
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,INTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://127.0.0.1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
      - KAFKA_INTER_BROKER_USER=${CLIENT_USER}
      - KAFKA_INTER_BROKER_PASSWORD=${CLIENT_PASSWORD}
      - KAFKA_CLIENT_USERS=${CLIENT_USER}
      - KAFKA_CLIENT_PASSWORDS=${CLIENT_PASSWORD}
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data/mongo:/data/db
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aioshima
      - POSTGRES_DB=example
  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASS}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    depends_on:
      - postgres
  # krakend:
  #   image: devopsfaith/krakend:latest
  #   restart: unless-stopped
  #   container_name: krakend
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - .:/etc/krakend/